import Foundation

/// Compact pinyin → candidate lookup for the keyboard's 中文 typing mode.
///
/// ## What this is
/// A **small built-in lexicon** (syllables + common bigrams/phrases) with
/// longest-match / greedy segmentation so buffers like `nihao` → 你好 and
/// `woaini` → 我爱你 without typing char-by-char.
///
/// ## Limits (honest)
/// - Not a full IME: no cloud dict, no personalization, no fuzzy pinyin,
///   no tone marks, no huge phrase DB (keeps the keyboard extension small).
/// - Unknown compounds fall back to longest table prefix, then single syllables.
/// - Selecting a candidate inserts that text and **consumes only the matched
///   pinyin prefix**, leaving any unmatched suffix in the buffer when possible.
/// - Good enough for daily chat / short messages; not a Sogou/Baidu replacement.
enum PinyinIME {
    /// One candidate row entry: Chinese text + how many pinyin letters it consumes.
    struct Candidate: Equatable {
        let text: String
        let consumed: Int
    }

    /// Returns candidates for a lowercase pinyin buffer (letters only).
    /// Order: exact phrase → longest prefix hits → greedy full-buffer compose → shorter prefixes.
    static func candidates(for buffer: String) -> [Candidate] {
        let key = buffer.lowercased().filter { $0.isLetter }
        guard !key.isEmpty else { return [] }

        var out: [Candidate] = []
        var seen = Set<String>()

        func append(_ text: String, consumed: Int) {
            guard consumed > 0, !text.isEmpty, !seen.contains(text) else { return }
            seen.insert(text)
            out.append(Candidate(text: text, consumed: consumed))
        }

        // 1) Exact table hit
        if let exact = table[key] {
            for w in exact { append(w, consumed: key.count) }
        }

        // 2) Longest table keys that are prefixes of `key` (phrases before short syllables)
        let prefixKeys = table.keys
            .filter { key.hasPrefix($0) && $0 != key }
            .sorted { $0.count > $1.count }
        for pk in prefixKeys.prefix(8) {
            if let words = table[pk] {
                for w in words.prefix(4) { append(w, consumed: pk.count) }
            }
            if out.count >= 12 { return Array(out.prefix(12)) }
        }

        // 3) Greedy full-buffer segmentation → composed candidate when useful
        if let composed = greedyCompose(key), composed.consumed == key.count, composed.text.count > 1 {
            append(composed.text, consumed: composed.consumed)
        }

        // 4) Prefix completion: table keys that start with buffer (still typing)
        if key.count >= 2 {
            for (pinyin, words) in table where pinyin.hasPrefix(key) && pinyin != key {
                for w in words {
                    append(w, consumed: key.count)
                    if out.count >= 12 { return Array(out.prefix(12)) }
                }
            }
        }

        return Array(out.prefix(12))
    }

    /// Longest-match greedy: repeatedly take the longest table key at the front.
    private static func greedyCompose(_ key: String) -> Candidate? {
        var rest = key
        var parts: [String] = []
        var consumed = 0
        while !rest.isEmpty {
            guard let match = longestPrefixKey(in: rest),
                  let word = table[match]?.first else { break }
            parts.append(word)
            consumed += match.count
            rest = String(rest.dropFirst(match.count))
        }
        guard consumed > 0, !parts.isEmpty else { return nil }
        return Candidate(text: parts.joined(), consumed: consumed)
    }

    private static func longestPrefixKey(in key: String) -> String? {
        var best: String?
        for pinyin in table.keys where key.hasPrefix(pinyin) {
            if best == nil || pinyin.count > best!.count { best = pinyin }
        }
        return best
    }

    /// Syllables + common daily bigrams/phrases. Modest size — not a full IME dump.
    private static let table: [String: [String]] = [
        // --- syllables ---
        "a": ["啊", "阿"],
        "e": ["额", "饿"],
        "o": ["哦", "噢"],
        "ai": ["爱", "唉", "艾"],
        "an": ["安", "按"],
        "ao": ["奥", "傲"],
        "ba": ["吧", "把", "爸", "八"],
        "bi": ["比", "笔", "必", "闭"],
        "bo": ["波", "播"],
        "bu": ["不", "步", "部"],
        "ca": ["擦"],
        "ce": ["测", "侧", "册"],
        "ci": ["次", "词", "此"],
        "cu": ["粗", "促"],
        "da": ["大", "打", "答"],
        "de": ["的", "得", "地"],
        "di": ["地", "第", "低", "弟"],
        "du": ["读", "独", "度", "赌"],
        "en": ["嗯", "恩"],
        "er": ["而", "二", "儿", "耳"],
        "fa": ["发", "法"],
        "fo": ["佛"],
        "fu": ["副", "服", "父", "付", "富"],
        "ga": ["嘎"],
        "ge": ["个", "各", "歌", "哥"],
        "gu": ["古", "故", "顾", "股"],
        "ha": ["哈"],
        "he": ["和", "河", "合", "何"],
        "hu": ["湖", "护", "户", "互"],
        "ji": ["机", "记", "几", "己", "及", "即"],
        "ju": ["句", "局", "居", "举"],
        "ka": ["卡", "咖"],
        "ke": ["可", "课", "克", "科"],
        "ku": ["苦", "哭", "库"],
        "la": ["啦", "拉", "辣"],
        "le": ["了", "乐"],
        "li": ["里", "理", "力", "立", "利", "离"],
        "lu": ["路", "录", "炉"],
        "lv": ["绿", "旅", "律"],
        "ma": ["吗", "妈", "马", "嘛"],
        "me": ["么"],
        "mi": ["米", "密", "迷"],
        "mo": ["莫", "摸", "末", "魔"],
        "mu": ["目", "母", "木", "暮"],
        "na": ["那", "拿", "哪"],
        "ne": ["呢"],
        "ni": ["你", "尼", "泥"],
        "nu": ["怒", "努"],
        "nv": ["女"],
        "ou": ["欧", "偶"],
        "pa": ["怕", "爬"],
        "pi": ["皮", "批", "啤"],
        "po": ["破", "坡", "迫"],
        "pu": ["普", "铺", "扑"],
        "qi": ["起", "其", "七", "气", "奇", "期"],
        "qu": ["去", "取", "区", "趣"],
        "re": ["热"],
        "ri": ["日"],
        "ru": ["如", "入", "乳"],
        "sa": ["撒", "洒"],
        "se": ["色", "涩"],
        "si": ["四", "思", "死", "司"],
        "su": ["素", "速", "诉", "苏"],
        "ta": ["他", "她", "它", "塔"],
        "te": ["特"],
        "ti": ["提", "体", "题", "替"],
        "tu": ["图", "土", "突"],
        "wa": ["哇", "挖", "娃"],
        "wo": ["我", "握", "卧"],
        "wu": ["五", "无", "物", "务", "屋"],
        "xi": ["西", "喜", "系", "息", "希", "习"],
        "xu": ["许", "续", "需", "虚"],
        "ya": ["呀", "牙", "压", "亚"],
        "ye": ["也", "页", "业", "夜", "叶"],
        "yi": ["一", "以", "已", "意", "易", "医"],
        "yo": ["哟"],
        "yu": ["与", "于", "语", "雨", "鱼", "遇"],
        "za": ["杂", "砸"],
        "ze": ["则", "责", "择"],
        "zi": ["子", "字", "自", "资"],
        "zu": ["组", "足", "族", "祖"],
        "ang": ["昂"],
        "bai": ["白", "百", "摆"],
        "ban": ["办", "半", "班"],
        "bao": ["包", "报", "保", "宝"],
        "bei": ["被", "北", "倍", "杯"],
        "ben": ["本"],
        "bie": ["别"],
        "cai": ["才", "菜", "彩"],
        "can": ["参", "残"],
        "cao": ["草", "操"],
        "cha": ["查", "茶", "差"],
        "che": ["车", "彻"],
        "chi": ["吃", "尺", "迟"],
        "chu": ["出", "处", "初"],
        "cui": ["催", "脆"],
        "cun": ["村", "存"],
        "cuo": ["错", "措"],
        "dai": ["带", "代", "呆"],
        "dan": ["但", "单", "蛋", "淡"],
        "dao": ["到", "道", "倒", "岛"],
        "dei": ["得"],
        "die": ["跌", "叠"],
        "dou": ["都", "豆", "斗"],
        "dui": ["对", "队"],
        "dun": ["顿", "盾"],
        "duo": ["多", "躲"],
        "fan": ["反", "饭", "烦", "凡"],
        "fei": ["飞", "非", "费"],
        "fen": ["分", "份", "粉"],
        "fou": ["否"],
        "gai": ["该", "改", "盖"],
        "gan": ["干", "感", "敢"],
        "gao": ["高", "搞", "告"],
        "gei": ["给"],
        "gen": ["跟", "根"],
        "gou": ["够", "狗", "购"],
        "gua": ["挂", "瓜"],
        "gui": ["贵", "归", "鬼", "规"],
        "gun": ["滚"],
        "guo": ["过", "国", "果"],
        "hai": ["还", "海", "害", "孩"],
        "han": ["汉", "含", "寒"],
        "hao": ["好", "号", "毫"],
        "hei": ["黑", "嘿"],
        "hen": ["很", "恨"],
        "hou": ["后", "候", "厚"],
        "hua": ["话", "花", "化", "华", "画"],
        "hui": ["会", "回", "灰", "慧"],
        "hun": ["混", "婚"],
        "huo": ["或", "活", "火", "货"],
        "jia": ["家", "加", "假", "价"],
        "jie": ["接", "结", "解", "姐", "界"],
        "jin": ["进", "近", "金", "今", "紧"],
        "jiu": ["就", "九", "久", "酒", "旧"],
        "jue": ["觉", "决", "绝"],
        "jun": ["军", "均"],
        "kai": ["开", "凯"],
        "kan": ["看", "砍"],
        "kao": ["靠", "考"],
        "ken": ["肯", "垦"],
        "kou": ["口", "扣"],
        "kua": ["夸", "跨"],
        "kui": ["亏", "愧"],
        "kun": ["困", "坤"],
        "kuo": ["扩", "阔"],
        "lai": ["来", "赖"],
        "lan": ["蓝", "懒", "栏"],
        "lao": ["老", "劳", "牢"],
        "lei": ["累", "类", "泪"],
        "lie": ["列", "烈"],
        "lin": ["林", "临", "邻"],
        "liu": ["六", "留", "流", "刘"],
        "lou": ["楼", "漏"],
        "lue": ["略"],
        "lun": ["论", "轮"],
        "luo": ["落", "罗", "洛"],
        "mai": ["买", "卖", "麦"],
        "man": ["满", "慢", "蛮"],
        "mao": ["毛", "猫", "冒"],
        "mei": ["没", "美", "每", "妹"],
        "men": ["们", "门"],
        "mie": ["灭"],
        "min": ["民", "敏"],
        "miu": ["谬"],
        "mou": ["某"],
        "nai": ["奶", "耐"],
        "nan": ["难", "男", "南"],
        "nao": ["脑", "闹"],
        "nei": ["内"],
        "nen": ["嫩"],
        "nie": ["捏"],
        "nin": ["您"],
        "niu": ["牛", "扭"],
        "nue": ["虐"],
        "nuo": ["诺", "挪"],
        "pai": ["排", "拍", "派"],
        "pan": ["盘", "判", "盼"],
        "pao": ["跑", "炮", "泡"],
        "pei": ["配", "陪", "培"],
        "pen": ["喷"],
        "pie": ["撇"],
        "pin": ["品", "拼"],
        "pou": ["剖"],
        "qia": ["恰", "掐"],
        "qie": ["且", "切", "窃"],
        "qin": ["亲", "勤", "琴"],
        "qiu": ["求", "球", "秋"],
        "que": ["却", "确", "缺"],
        "qun": ["群"],
        "ran": ["然", "染"],
        "rao": ["绕", "扰"],
        "ren": ["人", "认", "任"],
        "rou": ["肉", "柔"],
        "rui": ["瑞", "锐"],
        "run": ["润"],
        "ruo": ["若", "弱"],
        "sai": ["赛", "塞"],
        "san": ["三", "散"],
        "sao": ["扫", "骚"],
        "sen": ["森"],
        "sha": ["啥", "杀", "沙"],
        "she": ["社", "设", "射", "舍"],
        "shi": ["是", "时", "十", "事", "实", "市", "师"],
        "shu": ["书", "数", "树", "熟"],
        "sou": ["搜", "艘"],
        "sui": ["虽", "随", "岁", "碎"],
        "sun": ["孙", "损"],
        "suo": ["所", "锁", "缩"],
        "tai": ["太", "台", "态"],
        "tan": ["谈", "弹", "贪"],
        "tao": ["套", "逃", "讨", "桃"],
        "tie": ["贴", "铁"],
        "tou": ["头", "偷", "透"],
        "tui": ["退", "推", "腿"],
        "tun": ["吞", "屯"],
        "tuo": ["托", "脱", "拖"],
        "wai": ["外", "歪"],
        "wan": ["完", "玩", "晚", "万", "碗"],
        "wei": ["为", "位", "未", "微", "喂", "伟"],
        "wen": ["文", "问", "闻", "稳"],
        "xia": ["下", "夏", "吓", "狭"],
        "xie": ["写", "些", "谢", "鞋", "协"],
        "xin": ["新", "心", "信", "欣"],
        "xiu": ["修", "休", "秀"],
        "xue": ["学", "雪", "血"],
        "xun": ["寻", "训", "迅"],
        "yan": ["眼", "言", "严", "研", "演"],
        "yao": ["要", "药", "姚", "摇", "腰"],
        "yin": ["因", "音", "银", "引", "阴"],
        "you": ["有", "又", "右", "友", "由", "游"],
        "yue": ["月", "乐", "越", "约"],
        "yun": ["云", "运", "允"],
        "zai": ["在", "再", "载"],
        "zan": ["咱", "赞", "暂"],
        "zao": ["早", "造", "糟"],
        "zei": ["贼"],
        "zen": ["怎"],
        "zha": ["炸", "扎", "眨"],
        "zhe": ["这", "着", "者"],
        "zhi": ["之", "只", "知", "直", "制", "纸"],
        "zhu": ["住", "主", "注", "助", "诸"],
        "zou": ["走"],
        "zui": ["最", "嘴", "罪"],
        "zun": ["尊"],
        "zuo": ["做", "作", "坐", "左", "昨"],
        "bang": ["帮", "棒"],
        "bian": ["边", "变", "便"],
        "biao": ["表", "标"],
        "bing": ["并", "病", "冰"],
        "cang": ["藏"],
        "ceng": ["曾", "层"],
        "chai": ["拆"],
        "chan": ["产", "缠"],
        "chao": ["超", "朝", "抄"],
        "chen": ["陈", "沉"],
        "chou": ["抽", "愁"],
        "chui": ["吹"],
        "chun": ["春", "纯"],
        "cong": ["从", "聪"],
        "cuan": ["窜"],
        "dang": ["当", "党"],
        "deng": ["等", "灯", "登"],
        "dian": ["点", "电", "店"],
        "diao": ["掉", "调"],
        "ding": ["定", "顶", "订"],
        "dong": ["东", "懂", "动", "冬"],
        "duan": ["段", "短", "断"],
        "fang": ["方", "放", "房", "防"],
        "feng": ["风", "封", "疯"],
        "gang": ["刚", "钢", "港"],
        "geng": ["更"],
        "gong": ["工", "公", "共", "功"],
        "guai": ["怪", "乖"],
        "guan": ["关", "管", "官", "观"],
        "hang": ["行", "航"],
        "heng": ["横", "恒"],
        "hong": ["红", "轰"],
        "huai": ["坏", "怀"],
        "huan": ["换", "还", "欢", "环"],
        "jian": ["见", "间", "件", "简", "建"],
        "jiao": ["教", "叫", "交", "较", "脚"],
        "jing": ["经", "精", "京", "静", "景"],
        "juan": ["卷", "捐"],
        "kang": ["康", "抗"],
        "keng": ["坑"],
        "kong": ["空", "恐", "控"],
        "kuai": ["快", "块"],
        "kuan": ["宽", "款"],
        "lang": ["浪", "郎", "朗"],
        "leng": ["冷"],
        "lian": ["连", "脸", "练", "联"],
        "liao": ["了", "料", "聊"],
        "ling": ["另", "零", "领", "灵"],
        "long": ["龙", "弄"],
        "luan": ["乱"],
        "mang": ["忙", "盲"],
        "meng": ["梦", "猛", "盟"],
        "mian": ["面", "免", "棉"],
        "miao": ["秒", "妙", "描"],
        "ming": ["明", "名", "命"],
        "nang": ["囊"],
        "neng": ["能"],
        "nian": ["年", "念"],
        "niao": ["鸟", "尿"],
        "ning": ["宁", "凝"],
        "nong": ["农", "弄"],
        "nuan": ["暖"],
        "pang": ["旁", "胖"],
        "peng": ["朋", "碰", "捧"],
        "pian": ["片", "偏", "骗"],
        "piao": ["票", "飘"],
        "ping": ["平", "评", "瓶"],
        "qian": ["前", "钱", "千", "签"],
        "qiao": ["桥", "巧", "悄"],
        "qing": ["请", "清", "情", "轻", "青"],
        "quan": ["全", "权", "泉"],
        "rang": ["让"],
        "reng": ["仍", "扔"],
        "rong": ["容", "荣", "融"],
        "ruan": ["软"],
        "sang": ["桑", "丧"],
        "seng": ["僧"],
        "shai": ["晒"],
        "shan": ["山", "善", "闪"],
        "shao": ["少", "烧", "绍"],
        "shei": ["谁"],
        "shen": ["什", "身", "深", "神", "甚"],
        "shou": ["手", "受", "收", "首"],
        "shua": ["刷", "耍"],
        "shui": ["谁", "水", "睡"],
        "shun": ["顺"],
        "shuo": ["说"],
        "song": ["送", "松", "宋"],
        "suan": ["算", "酸"],
        "tang": ["汤", "躺", "糖", "唐"],
        "teng": ["疼", "腾"],
        "tian": ["天", "田", "填"],
        "tiao": ["条", "跳", "调"],
        "ting": ["听", "停", "庭"],
        "tong": ["同", "通", "痛", "童"],
        "tuan": ["团"],
        "wang": ["往", "网", "王", "忘", "望"],
        "weng": ["翁"],
        "xian": ["先", "现", "线", "显", "县"],
        "xiao": ["小", "笑", "消", "校", "效"],
        "xing": ["行", "性", "姓", "星", "兴", "形"],
        "xuan": ["选", "宣", "玄"],
        "yang": ["样", "阳", "杨", "养", "羊"],
        "ying": ["应", "影", "英", "迎", "硬"],
        "yong": ["用", "永", "勇", "拥"],
        "yuan": ["原", "员", "远", "院", "元", "愿"],
        "zang": ["脏", "藏"],
        "zeng": ["增", "曾"],
        "zhai": ["摘", "窄"],
        "zhan": ["站", "战", "占", "展"],
        "zhao": ["找", "着", "照", "赵"],
        "zhen": ["真", "镇", "针", "阵"],
        "zhou": ["周", "州", "舟"],
        "zhua": ["抓"],
        "zhui": ["追", "坠"],
        "zhun": ["准"],
        "zhuo": ["桌", "着", "捉"],
        "zong": ["总", "宗", "纵"],
        "zuan": ["钻"],
        "chang": ["长", "常", "场", "唱"],
        "cheng": ["成", "城", "程", "称"],
        "chong": ["冲", "重", "充"],
        "chuan": ["传", "船", "穿"],
        "guang": ["光", "广"],
        "huang": ["黄", "慌", "皇"],
        "jiang": ["将", "讲", "江", "奖"],
        "jiong": ["窘"],
        "kuang": ["况", "狂", "矿"],
        "liang": ["两", "亮", "量", "凉"],
        "niang": ["娘"],
        "qiang": ["强", "墙", "抢"],
        "qiong": ["穷"],
        "shang": ["上", "商", "伤"],
        "sheng": ["生", "声", "省", "升"],
        "shuai": ["帅", "摔"],
        "shuan": ["栓"],
        "xiang": ["想", "向", "像", "相", "香", "箱"],
        "xiong": ["兄", "雄", "胸"],
        "zhang": ["张", "长", "掌", "丈"],
        "zheng": ["正", "整", "争", "政"],
        "zhong": ["中", "种", "重", "众"],
        "zhuai": ["拽"],
        "zhuan": ["转", "专", "传"],
        "chuang": ["创", "床", "窗"],
        "shuang": ["双", "爽"],
        "zhuang": ["装", "状", "庄"],
        // --- phrases ---
        "nar": ["哪儿"],
        "aini": ["爱你"],
        "baba": ["爸爸"],
        "didi": ["弟弟"],
        "erzi": ["儿子"],
        "gege": ["哥哥"],
        "jixu": ["继续"],
        "kehu": ["客户"],
        "keyi": ["可以"],
        "mama": ["妈妈"],
        "mima": ["密码"],
        "nage": ["那个", "哪个"],
        "nali": ["哪里", "那里"],
        "nide": ["你的"],
        "nver": ["女儿"],
        "tade": ["他的", "她的"],
        "woai": ["我爱"],
        "wode": ["我的"],
        "ziji": ["自己"],
        "buhao": ["不好"],
        "bushi": ["不是"],
        "buyao": ["不要"],
        "dajia": ["大家"],
        "haipa": ["害怕"],
        "haizi": ["孩子"],
        "hanyu": ["汉语"],
        "haode": ["好的"],
        "huida": ["回答"],
        "huiyi": ["会议"],
        "kafei": ["咖啡"],
        "lijie": ["理解"],
        "mafan": ["麻烦"],
        "nihao": ["你好"],
        "nimen": ["你们"],
        "nvren": ["女人"],
        "tamen": ["他们", "她们"],
        "wanan": ["晚安"],
        "wanyi": ["万一"],
        "wenti": ["问题"],
        "women": ["我们"],
        "wucan": ["午餐"],
        "xiuxi": ["休息"],
        "xuyao": ["需要"],
        "yihou": ["以后"],
        "yixia": ["一下"],
        "youxi": ["游戏"],
        "zenme": ["怎么"],
        "zhege": ["这个"],
        "zheli": ["这里"],
        "zhuce": ["注册"],
        "zhuyi": ["注意"],
        "zouba": ["走吧"],
        "baocun": ["保存"],
        "baogao": ["报告"],
        "bukeqi": ["不客气"],
        "buneng": ["不能"],
        "buxing": ["不行"],
        "chifan": ["吃饭"],
        "chumen": ["出门"],
        "denglu": ["登录"],
        "difang": ["地方"],
        "dongxi": ["东西"],
        "fandui": ["反对"],
        "fanhui": ["返回"],
        "fasong": ["发送"],
        "ganxie": ["感谢"],
        "gongsi": ["公司"],
        "gongxi": ["恭喜"],
        "haochi": ["好吃"],
        "haokan": ["好看"],
        "haowan": ["好玩"],
        "henhao": ["很好"],
        "heshui": ["喝水"],
        "huijia": ["回家"],
        "jiayou": ["加油"],
        "jiejie": ["姐姐"],
        "jieshu": ["结束"],
        "kaishi": ["开始"],
        "kaixin": ["开心"],
        "keneng": ["可能"],
        "kuaile": ["快乐"],
        "laoshi": ["老师"],
        "mafani": ["麻烦你"],
        "manzou": ["慢走"],
        "meiguo": ["美国"],
        "meimei": ["妹妹"],
        "meishi": ["没事"],
        "meiyou": ["没有"],
        "nanguo": ["难过"],
        "nanren": ["男人"],
        "pianyi": ["便宜"],
        "quxiao": ["取消"],
        "shenme": ["什么"],
        "shibai": ["失败"],
        "shouji": ["手机"],
        "sousuo": ["搜索"],
        "taigui": ["太贵"],
        "taihao": ["太好"],
        "tongyi": ["同意"],
        "wancan": ["晚餐"],
        "weixin": ["微信"],
        "woaini": ["我爱你"],
        "xiaban": ["下班"],
        "xiaoxi": ["消息"],
        "xiexie": ["谢谢"],
        "xihuan": ["喜欢"],
        "xiugai": ["修改"],
        "yidian": ["一点"],
        "yiding": ["一定"],
        "yingyu": ["英语"],
        "yinyue": ["音乐"],
        "yiqian": ["以前"],
        "yiyuan": ["医院"],
        "zaocan": ["早餐"],
        "zhende": ["真的"],
        "zhichi": ["支持"],
        "zhidao": ["知道"],
        "bangzhu": ["帮助"],
        "baoqian": ["抱歉"],
        "beijing": ["北京"],
        "bushiba": ["不是吧"],
        "canting": ["餐厅"],
        "dengdai": ["等待"],
        "dianhua": ["电话"],
        "diannao": ["电脑"],
        "duibuqi": ["对不起"],
        "duoshao": ["多少"],
        "gongzuo": ["工作"],
        "haoting": ["好听"],
        "jintian": ["今天"],
        "jiudian": ["酒店"],
        "kanjian": ["看见"],
        "mingbai": ["明白"],
        "nihaoma": ["你好吗"],
        "pengyou": ["朋友"],
        "pingguo": ["苹果"],
        "qingchu": ["清楚"],
        "qingjin": ["请进"],
        "qingwen": ["请问"],
        "qingzuo": ["请坐"],
        "queding": ["确定"],
        "shanchu": ["删除"],
        "shengqi": ["生气"],
        "shengri": ["生日"],
        "shijian": ["时间", "事件"],
        "shuiguo": ["水果"],
        "shuohua": ["说话"],
        "tingdao": ["听到"],
        "tongshi": ["同事"],
        "tongxue": ["同学"],
        "wenjian": ["文件"],
        "xianzai": ["现在"],
        "xiaoxin": ["小心"],
        "xinnian": ["新年"],
        "xuexiao": ["学校"],
        "yinggai": ["应该"],
        "yundong": ["运动"],
        "zaijian": ["再见"],
        "zhenhao": ["真好"],
        "zuotian": ["昨天"],
        "baozhong": ["保重"],
        "buzhidao": ["不知道"],
        "dengdeng": ["等等"],
        "dianying": ["电影"],
        "duibudui": ["对不对"],
        "feichang": ["非常"],
        "haibuhao": ["好不好"],
        "jiankang": ["健康"],
        "kuaidian": ["快点"],
        "meishier": ["没事儿"],
        "meiwenti": ["没问题"],
        "mingtian": ["明天"],
        "qichuang": ["起床"],
        "shangban": ["上班"],
        "shanghai": ["上海"],
        "shibushi": ["是不是"],
        "shuijiao": ["睡觉"],
        "wancheng": ["完成"],
        "xiangyao": ["想要"],
        "xuesheng": ["学生"],
        "youxiang": ["邮箱"],
        "zhongguo": ["中国"],
        "zhongwen": ["中文"],
        "chenggong": ["成功"],
        "dengyixia": ["等一下"],
        "meiguanxi": ["没关系"],
        "weishenme": ["为什么"],
        "xiangjiao": ["香蕉"],
        "youmeiyou": ["有没有"],
        "yuanliang": ["原谅"],
        "zenmeyang": ["怎么样"],
        "nengbuneng": ["能不能"],
        "xingbuxing": ["行不行"],
        "duoshaoqian": ["多少钱"],
        "nidepengyou": ["你的朋友"],
        "wanshanghao": ["晚上好"],
        "wodepengyou": ["我的朋友"],
        "zaoshanghao": ["早上好"],
        "haojiubujian": ["好久不见"],
        "mingtianjian": ["明天见"],
        "shengrikuaile": ["生日快乐"],
        "xinniankuaile": ["新年快乐"],
    ]
}
